const $=(selector,parent=document)=>parent.querySelector(selector);
const $$=(selector,parent=document)=>[...parent.querySelectorAll(selector)];
const toast=message=>{const el=$('.toast');el.textContent=message;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),2200)};

const rooms={
  carry:{label:'01 / FULL CARRY',title:'구성은 곧, 짧은 자기소개.',description:'사진 속 물건마다 “왜 이걸 골랐는지”를 붙입니다. 브랜드 목록이 한 사람의 생활 방식으로 읽히기 시작해요.',visual:`<div class="room-visual"><img src="assets/edc-flatlay.png" alt="다양한 일상 휴대품을 펼쳐놓은 플랫레이"><div class="visual-shade"></div><span class="visual-label">LITERAL EDC · SEOUL</span><button class="hotspot spot-1 active" data-label="R10 MINI · 어두운 귀갓길">01</button><button class="hotspot spot-2" data-label="CARD CASE · 주머니가 얇게">02</button><button class="hotspot spot-3" data-label="A6 NOTE · 기억은 손으로">03</button><button class="hotspot spot-4" data-label="MULTI TOOL · 직접 고치기">04</button><div class="visual-story"><h3>기계는 좋아하지만<br>주머니는 가볍게.</h3><div class="stats"><span><b>472g</b>TOTAL</span><span><b>7</b>ITEMS</span><span><b>4.2y</b>AVG. AGE</span></div></div></div>`,reasons:['바꾸기보다 길들이는 편','검정과 회색, 단 한 점의 주황','대중교통 출퇴근에 맞춘 500g 아래'],author:'민규 · 제품 디자이너',meta:'서울 · 이 구성 214일째'},
  light:{label:'02 / LIGHT ROOM',title:'스펙은 숫자, 빛은 경험.',description:'같은 장소에서 찍은 빔샷과 실제 설정을 겹쳐 봅니다. 루멘보다 내가 걷는 길에 맞는 빛을 이야기해요.',visual:`<div class="mode-visual beam-scene"><div class="mode-header"><span>BEAM WALL / HAN RIVER 22:14</span><span>ISO 400 · 1/30S · WB 4800K</span></div><div class="beam-tree"></div><div class="beam-cone" id="beamCone"></div><div class="beam-readout"><strong id="beamValue">480<span>lm</span></strong><span id="beamDistance">40m에서 중심광이 선명함</span><div class="beam-modes"><button data-beam="low">LOW</button><button class="active" data-beam="mid">MID</button><button data-beam="turbo">TURBO</button></div></div></div>`,reasons:['퇴근길 30분 동안 MID 고정','넓은 산책로라 중심광보다 주변광','겨울 장갑에도 찾기 쉬운 측면 버튼'],author:'서아 · 야간 산책자',meta:'인천 · 8개월 실사용'},
  bag:{label:'03 / PACK ROOM',title:'몇 리터보다, 어디에 무엇을.',description:'가방 안을 수납 지도로 그립니다. 자주 꺼내는 물건, 한 손 접근, 비 오는 날의 동선을 서로 비교해요.',visual:`<div class="mode-visual pack-scene"><div class="mode-header"><span>PACK MAP / 6L SLING</span><span>LOAD 1.14KG · 82% FULL</span></div><span class="access-path">ZIP OPEN → ONE HAND ACCESS</span><div class="bag-shell"><div class="pack-zone hot"><span><b>3×</b>하루 접근<br>지갑 · 이어폰</span></div><div class="pack-zone"><span><b>1×</b>필요할 때<br>케이블 파우치</span></div><div class="pack-zone long"><span><b>LONG</b>A6 노트 · 접이식 우산 · 보조배터리</span></div></div></div>`,reasons:['오른손으로 멘 채 지갑까지 4초','우산이 젖어도 전자기기와 분리','비어 있는 18%가 충동구매 방지선'],author:'우진 · 자전거 출퇴근',meta:'서울 · 6L 슬링 131일'},
  tool:{label:'04 / TOOL BENCH',title:'소유보다, 해결한 일의 기록.',description:'날카로운 스펙 대신 실제로 무엇을 고치고 만들었는지 쌓습니다. 마모와 수리도 이 도구의 이력이 됩니다.',visual:`<div class="mode-visual tool-scene"><div class="mode-header"><span>WORK LOG / SEPTEMBER</span><span>VERIFIED BY 24 USERS</span></div><div class="workbench"><div class="work-note"><small>09.02 · 08:41</small><strong>느슨한 자전거<br>브레이크 조정</strong>4mm 비트 · 7분</div><div class="work-note"><small>08.28 · 19:12</small><strong>친구의 의자<br>나사 다시 조임</strong>PH2 비트 · 12분</div><div class="work-note"><div><small>218 DAYS IN POCKET</small><strong>이 도구가 해결한 일</strong></div><div class="work-count">37</div></div></div></div>`,reasons:['플라이어 유격은 생겼지만 작업엔 문제없음','드라이버 비트 2개만 골라 무게 절약','칼날 관련 기록은 장소별 안전 안내와 함께'],author:'도현 · 무대 기술자',meta:'부산 · 수리 기록 37개'},
  write:{label:'05 / WRITING DESK',title:'필기감은, 직접 남겨야 보인다.',description:'같은 종이 위의 획, 잉크 마름, 손의 압력을 공유합니다. 예쁜 펜 사진이 실제 쓰는 감각으로 이어져요.',visual:`<div class="mode-visual write-scene"><div class="mode-header"><span>WRITING SAMPLE / A6 80GSM</span><span>LEFT HAND · LOW PRESSURE</span></div><div class="paper-sheet"><p>기억은 주머니보다<br>먼저 가벼워진다.</p><div class="ink-line"></div><div class="ink-line"></div><div class="ink-line"></div><div class="nib-score"><span>부드러움<b>8.6</b></span><span>마름 속도<b>12s</b></span><span>번짐<b>LOW</b></span></div></div></div>`,reasons:['작은 글씨에도 한글 획이 뭉치지 않음','왼손으로 써도 12초면 충분히 마름','황동 몸체의 무게가 낮은 필압에 잘 맞음'],author:'하림 · 에디터',meta:'대전 · 11개월 사용'}
};

const renderRoom=key=>{const room=rooms[key];$('#roomStage').innerHTML=`<div class="room-layout"><div class="room-main">${room.visual}</div><aside class="room-side"><p class="overline">${room.label}</p><h3>${room.title}</h3><p>${room.description}</p><div class="author-box"><span class="avatar coral">${room.author[0]}</span><div><strong>${room.author}</strong><small>${room.meta}</small></div><button aria-label="작성자 더보기">···</button></div><div class="reason-list">${room.reasons.map((item,index)=>`<span><b>0${index+1}</b>${item}</span>`).join('')}</div><div class="room-side-actions"><button data-join-room="${key}">이 방에서 놀기 →</button><button class="save-room" aria-label="저장">＋</button></div></aside></div>`;wireRoomInteractions();};

const wireRoomInteractions=()=>{
  $$('.hotspot').forEach(button=>button.addEventListener('click',()=>{$$('.hotspot').forEach(x=>x.classList.remove('active'));button.classList.add('active')}));
  $$('[data-beam]').forEach(button=>button.addEventListener('click',()=>{const values={low:['80','15m에서 발밑을 넓게',.55],mid:['480','40m에서 중심광이 선명함',.78],turbo:['1,200','72m까지 닿지만 90초 권장',1]};$$('[data-beam]').forEach(x=>x.classList.remove('active'));button.classList.add('active');const [value,text,scale]=values[button.dataset.beam];$('#beamValue').innerHTML=`${value}<span>lm</span>`;$('#beamDistance').textContent=text;$('#beamCone').style.opacity=scale}));
  $('[data-join-room]')?.addEventListener('click',()=>{const key=$('[data-join-room]').dataset.joinRoom;toast(`${rooms[key].title.replace('.', '')} 방에 입장했어요.`)});
  $('.save-room')?.addEventListener('click',event=>{event.currentTarget.textContent=event.currentTarget.textContent==='＋'?'✓':'＋';toast(event.currentTarget.textContent==='✓'?'이 방을 내 라운지에 저장했어요.':'저장을 취소했어요.')});
};

renderRoom('carry');
$$('[data-room]').forEach(button=>button.addEventListener('click',()=>{$$('[data-room]').forEach(x=>{x.classList.remove('active');x.setAttribute('aria-selected','false')});button.classList.add('active');button.setAttribute('aria-selected','true');renderRoom(button.dataset.room)}));

const composeDialog=$('#composeDialog');
$$('[data-open-compose]').forEach(button=>button.addEventListener('click',()=>composeDialog.showModal()));
$$('[data-compose-type]').forEach(button=>button.addEventListener('click',()=>{composeDialog.close();const label=$('b',button).textContent;toast(`${label}에 맞는 기록 도구를 열었어요.`)}));
$('#searchButton').addEventListener('click',()=>toast('“3L 출퇴근”, “따뜻한 빔”처럼 찾아보세요.'));

$$('[data-vote]').forEach(button=>button.addEventListener('click',()=>{const group=button.parentElement;if(group.classList.contains('voted'))return;group.classList.add('voted');$$('[data-vote]',group).forEach(item=>item.style.setProperty('--vote',`${item.dataset.vote}%`));toast('투표했어요. 서로 다른 72개의 이유가 열렸습니다.')}));

const matches=[['재영 · 무대 기술자','공통 취향 86% · 공통 장비 3','재'],['소은 · 북 디자이너','공통 취향 79% · 공통 장비 2','소'],['한결 · 자전거 정비사','공통 취향 73% · 공통 장비 4','한']];let matchIndex=0;
$('#shuffleMatch').addEventListener('click',()=>{matchIndex=(matchIndex+1)%matches.length;const [name,meta,initial]=matches[matchIndex];$('.match-person .avatar').textContent=initial;$('.match-person strong').textContent=name;$('.match-person small').textContent=meta;const score=meta.match(/\d+/)[0];$('.match-meter i').style.width=`${score}%`});
