const screens = {
  home: ['커뮤니티 홈', '좋은 도구, 좋은 사람들.', '인기 콘텐츠와 최신 이야기에서 시작하는 커뮤니티.'],
  board: ['게시판 목록', '경험이 쌓이는 게시판', '분류와 검색으로 글을 찾고, 읽기와 작성으로 이어집니다.'],
  detail: ['글 상세', '써본 이야기가 대화로', '사용기 본문, 공감, 댓글을 한 흐름으로 확인합니다.'],
  write: ['글쓰기', '나의 경험을 나누는 순간', '게시판 선택, 제목, 본문에 집중한 기본 작성 화면입니다.'],
  admin: ['관리자', '건강한 커뮤니티를 위한 운영', '게시글 공개 상태와 접수된 신고를 한 화면에서 관리합니다.']
};
const menus = {
  EDC: ['EDC 라운지', '오늘의 휴대품', '질문·답변', '신제품·소식'],
  GEAR: ['장비 정보', '사용기·리뷰', '관리·DIY', '메이커스 작업실'],
  'K-CRAFT': ['장인 이야기', '전통 휴대품', '생활 공예', '제작 과정', '작품·쇼룸'],
  LIFE: ['새 멤버 인사', '자유게시판', '유머 창고', '취미 생활', '호기심 연구소', '세상 이슈', '정치광장', '현장 제보'],
  'MARKET KR': ['개인 외부장터', '국내업체 장터', '공동구매', '거래후기'],
  GUIDE: ['공지사항', '이용안내', '운영정책', '신고·문의']
};
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const gearBody = '한 달 동안 출퇴근과 저녁 산책에 함께한 장비입니다. 처음에는 사양부터 비교했지만, 매일 써보니 주머니에서 꺼내기 편한지가 더 중요했습니다.\n\n01. 매일 휴대할 수 있는 크기\n무게가 가벼워 가방이 없는 날에도 부담이 적었습니다. 클립으로 고정하면 움직일 때도 안정적이었어요.\n\n02. 손에 익는 사용감\n자주 쓰는 기능에 바로 접근할 수 있어 좋았습니다. 다만 장갑을 끼고 조작할 때는 조금 더 적응이 필요했습니다.\n\n03. 한 달 뒤의 생각\n가장 뛰어난 사양보다 내 생활에 맞는 도구가 오래 남는 것 같습니다. 여러분은 어떤 기준으로 장비를 고르시나요?';
const entries = [...popular.map((p,i) => ({id:'popular-'+i,board:p[0],title:p[1],user:p[2],views:p[3],likes:Number(p[4]),comments:Number(p[5]),photo:pics[i],type:i%2?'정보':'사용기',body:gearBody})), ...posts.map((p,i) => ({id:'post-'+i,board:p[0]==='K-CRAFT'?'제작 과정':p[0],title:p[1],user:p[2],views:p[4],likes:Number(p[5]),comments:Number(p[6]),photo:pics[i%pics.length],type:i%2?'사용기':'정보',body:i===1?gearBody:'최근 사용하며 알게 된 경험을 공유합니다. '+p[1]+'\n\n매일 사용하는 환경을 기준으로 구성과 사용감을 기록해 보았습니다. 비슷한 경험이나 추천하고 싶은 방법이 있다면 댓글로 함께 이야기해 주세요.'}))];
entries.push({id:'notice',board:'공지사항',title:'9월 커뮤니티 운영 정책 안내',user:'운영팀',views:'1,240',likes:12,comments:0,type:'공지',body:'서로의 취향과 경험을 존중해 주세요.\n\n제품 사용기는 사용 환경과 기간을 함께 적어 주세요. 광고나 협찬이 포함된 글은 본문에 공개해 주세요.\n\n타인을 비방하거나 개인정보를 포함한 글은 검토 후 숨김 처리될 수 있습니다. 도움이 필요하면 게시글의 신고 기능을 이용해 주세요.'});
entries.push({id:'review-extra',board:'사용기·리뷰',title:'작은 멀티툴 하나로 충분했던 주말 캠핑',user:'outdoor_life',views:'482',likes:35,comments:7,photo:pics[0],type:'사용기',body:gearBody});
const reports = [{id:'r1',post:'post-3',reason:'광고·홍보 의심',note:'구매 링크가 반복되어 광고 여부 확인을 요청합니다.',count:2,status:'대기'}, {id:'r2',post:'popular-3',reason:'부적절한 표현',note:'본문의 일부 표현에 대한 운영 검토 요청입니다.',count:1,status:'대기'}];
let current = screens[location.hash.slice(1)] ? location.hash.slice(1) : 'home';
let board = '사용기·리뷰', selected = 'post-1', query = '', filter = '전체', sort = 0, latestGroup = '전체';
let adminTab = 'reports', reviewId = null, zoom = .75;
const liked = new Set(), comments = new Map();
let draft = {board:'사용기·리뷰',type:'사용기',title:'',body:''};
const getPost = id => entries.find(p=>p.id===id);
const goLink = (screen,label,cls='text-button') => `<a class="${cls}" href="#${screen}">${label}</a>`;
const postLink = (p,label=esc(p.title),cls='') => `<a class="${cls}" href="#detail" data-post="${p.id}">${label}</a>`;
function header(){return `<header class="top"><div class="wrap topline"><a class="mobile-menu" href="#board" aria-label="게시판 목록">☰</a><a class="brand" href="#home">EDC WORLD<small>PEOPLE · GEAR · A BETTER EVERYDAY</small></a><form class="search" data-search="global"><span>⌕</span><input name="query" placeholder="궁금한 장비와 이야기를 검색해 보세요." aria-label="통합검색"><button class="text-button">검색</button></form><span class="account">KR &nbsp; · &nbsp; ● 도윤</span></div><nav class="nav" aria-label="주요 메뉴"><div class="wrap navin">${Object.entries(menus).map(([group,items])=>`<div class="navitem ${items.includes(board)?'active':''}"><button class="navbtn" data-board="${items[0]}">${group}</button><div class="mega">${items.map(x=>`<a href="#board" data-board="${x}">${x}</a>`).join('')}</div></div>`).join('')}</div></nav></header>`}
function shell(body){return `${header()}<div class="app-main">${body}</div><footer class="app-footer"><strong>EDC WORLD</strong><span>People · Gear · A Better Everyday</span><span>서로의 취향을 존중하는 커뮤니티</span></footer><nav class="mobilebar" aria-label="모바일 메뉴">${goLink('home','⌂ 홈')}${goLink('board','▤ 게시판')}${goLink('write','＋ 글쓰기')}</nav>`}
function home(){
 const ranked=entries.filter(p=>p.id.startsWith('popular')&&!p.hidden).sort((a,b)=>sort===1?b.likes-a.likes:sort===2?Number(b.views.replaceAll(',',''))-Number(a.views.replaceAll(',','')):sort===3?b.comments-a.comments:0);
 const fresh=entries.filter(p=>(p.id.startsWith('post')||p.custom)&&!p.hidden&&(latestGroup==='전체'||menus[latestGroup]?.includes(p.board))).slice(0,6);
 return `<div class="notice-strip"><b>공지</b>${postLink(getPost('notice'))}<time>2026.09.12</time></div><div class="maincol"><section class="card"><div class="head"><span class="symbol">♨</span><h2>인기 콘텐츠</h2><div class="tabs">${['실시간','좋아요','많이 본','댓글 많은'].map((x,i)=>`<button class="tab ${sort===i?'on':''}" data-sort="${i}">${x}</button>`).join('')}</div>${goLink('board','더보기 〉','more')}</div>${ranked.map((p,i)=>`<article class="rankrow"><b class="ranknum ${i<3?'hot':''}">${i+1}</b><img class="thumb" src="${p.photo}" alt=""><span class="badge">${p.board}</span>${postLink(p,esc(p.title),'title')}<span class="meta">${p.user} · ${i+1}시간 전</span><span class="counts"><span>◉ ${p.views}</span><span class="heart">♡ ${p.likes}</span><span>◯ ${p.comments}</span></span></article>`).join('')}</section><section class="card"><div class="head"><span class="symbol">▤</span><h2>최신글</h2><div class="tabs">${['전체','EDC','GEAR','K-CRAFT','LIFE'].map(x=>`<button class="tab ${latestGroup===x?'on':''}" data-latest="${x}">${x}</button>`).join('')}</div>${goLink('board','더보기 〉','more')}</div>${fresh.map((p,i)=>`<article class="post"><img class="thumb" src="${p.photo||pics[i%5]}" alt=""><span class="badge">${esc(p.board)}</span>${postLink(p,esc(p.title),'title')}<span class="meta">${esc(p.user)} · ${p.custom?'방금 전':(i+1)+'시간 전'}</span><span class="counts"><span>◉ ${p.views}</span><span class="heart">♡ ${p.likes}</span><span>◯ ${p.comments}</span></span></article>`).join('')||'<p class="empty-state">아직 등록된 글이 없습니다.</p>'}</section><section class="card"><div class="head"><span class="symbol">▣</span><h2>오늘의 휴대품</h2><a class="more" href="#board" data-board="오늘의 휴대품">더보기 〉</a></div><div class="gallery">${pics.map((p,i)=>`<article class="carry">${postLink(getPost(i%2?'post-0':'popular-4'),`<img src="${p}" alt="오늘의 휴대품 ${i+1} 보기">`)}<div class="carrymeta"><span>♡ ${284-i*22}</span><span>◯ ${32-i*3}</span></div></article>`).join('')}</div></section><div class="featuregrid"><article class="card feature"><img src="https://images.unsplash.com/photo-1603899122634-f086ca5f5ddd?auto=format&fit=crop&w=600&q=80" alt="가죽 공예 작업"><div><h3>메이커스 작업실</h3><p>손으로 만드는 나만의 도구 이야기<br>메이커의 작업 과정을 만나보세요.</p></div><a href="#board" data-board="메이커스 작업실" aria-label="메이커스 작업실 보기">↗</a></article><article class="card feature"><img src="${pics[0]}" alt="나이프 작품"><div><h3>작품·쇼룸</h3><p>사람의 손에서 시작된 특별한 작품들<br>작품과 전시·행사를 둘러보세요.</p></div><a href="#board" data-board="작품·쇼룸" aria-label="작품·쇼룸 보기">↗</a></article></div></div>`;
}
function boardView(){
 const group=Object.entries(menus).find(([,items])=>items.includes(board))?.[0]||'GEAR';
 const list=entries.filter(p=>!p.hidden&&(board==='전체 게시판'||p.board===board)&&(filter==='전체'||p.type===filter)&&p.title.toLowerCase().includes(query.toLowerCase()));
 return `<div class="breadcrumb">커뮤니티 / ${esc(group)} / ${esc(board)}</div><div class="board-layout"><aside class="card board-rail"><h3>${group}</h3>${menus[group].map(x=>`<a href="#board" data-board="${x}" class="${x===board?'selected':''}">${x}</a>`).join('')}<a href="#board" data-board="전체 게시판">전체 게시판</a></aside><section><div class="page-title"><div><p class="eyebrow">COMMUNITY / BOARD</p><h1>${esc(board)}</h1><p>직접 써보고 알게 된 것들, 함께 나눠요.</p></div>${goLink('write','＋ 글쓰기','primary')}</div><div class="card"><div class="board-tools"><div class="chips">${['전체','사용기','정보'].map(x=>`<button class="chip ${x===filter?'on':''}" data-filter="${x}">${x}</button>`).join('')}</div><form class="board-search" data-search="board"><input name="query" aria-label="게시판 제목 검색" placeholder="제목으로 검색" value="${esc(query)}"><button class="secondary">검색</button></form></div><table class="post-table"><thead><tr><th scope="col">제목</th><th scope="col">작성자</th><th scope="col">작성일</th><th scope="col">조회</th></tr></thead><tbody>${list.map(p=>`<tr><td>${postLink(p,`<span class="row-category">${esc(p.type)}</span>${esc(p.title)}<span class="reply-count">${p.comments+(comments.get(p.id)?.length||0)}</span>`)}<span class="mobile-meta">${esc(p.user)} · 09.13 · 조회 ${p.views}</span></td><td>${esc(p.user)}</td><td>09.13</td><td>${p.views}</td></tr>`).join('')}</tbody></table>${!list.length?'<div class="empty-state">'+(query?'검색 결과가 없습니다.<br>다른 검색어로 찾아보세요.':'아직 등록된 글이 없습니다.<br>첫 번째 이야기를 남겨 주세요.')+'</div>':''}<div class="board-bottom"><span>${list.length}개의 글</span><span class="page-chip" aria-label="현재 1페이지">1</span><span>최신 작성순</span></div></div></section></div>`;
}
function detail(){const p=getPost(selected);if(p.hidden)return `<div class="card empty-state">운영 검토로 숨김 처리된 게시글입니다.<br><br>${goLink('board','목록으로','secondary')}</div>`;const added=comments.get(p.id)||[];return `<div class="reading"><div class="breadcrumb"><a href="#board" data-board="${esc(p.board)}">← ${esc(p.board)} 목록으로</a></div><article class="card"><div class="article-content"><span class="badge">${esc(p.board)} · ${esc(p.type)}</span><h1>${esc(p.title)}</h1><div class="authorline"><span class="avatar">${esc(p.user[0].toUpperCase())}</span><b>${esc(p.user)}</b><span>2026.09.13 10:24</span><span>조회 ${p.views} · 댓글 ${p.comments+added.length}</span></div>${p.photo?`<img class="article-photo" src="${p.photo}" alt="게시글에서 소개하는 장비">`:''}<div class="body-copy">${esc(p.body)}</div>${p.custom||p.type==='공지'?'':'<div class="article-note">개인 구매 후 직접 사용한 경험입니다.<br>사용 환경과 취향에 따라 느낌은 달라질 수 있어요.</div>'}<div class="reactions"><button class="secondary ${liked.has(p.id)?'on':''}" data-like="${p.id}" aria-pressed="${liked.has(p.id)}">${liked.has(p.id)?'♥':'♡'} 공감 ${p.likes+(liked.has(p.id)?1:0)}</button></div><div class="article-end"><a class="text-button" href="#board" data-board="${esc(p.board)}">← 목록으로</a><button class="text-button" data-report="${p.id}">신고</button></div></div><section class="thread"><h2>댓글 <span>${p.comments+added.length}</span></h2>${p.comments?'<div class="comment-row"><span class="avatar">캠</span><div><b>camp_diary</b><small>1시간 전</small><p>실제로 사용한 이야기가 도움이 되네요.<br>저도 휴대성을 가장 먼저 보게 되더라고요.</p></div></div><p class="meta">기존 댓글 중 대표 댓글 1개를 표시한 시안입니다.</p>':''}${added.map(c=>`<div class="comment-row"><span class="avatar">도</span><div><b>도윤</b><small>방금 전</small><p>${esc(c)}</p></div></div>`).join('')}<form class="comment-form" data-comment="${p.id}"><input name="comment" required maxlength="500" placeholder="경험을 나누는 댓글을 남겨 주세요." aria-label="댓글 입력"><button class="primary">등록</button></form></section></article></div>`}
function editor(){return `<form class="card editor" data-editor><div class="breadcrumb">${goLink('board','← 게시판으로')}</div><div class="editor-top"><div><p class="eyebrow">SHARE YOUR EXPERIENCE</p><h1>글쓰기</h1></div><button type="button" class="secondary" data-draft>임시 저장</button></div><div class="field-pair"><label class="field"><span>게시판</span><select name="board">${Object.entries(menus).map(([g,items])=>`<optgroup label="${g}">${items.map(x=>`<option ${draft.board===x?'selected':''}>${x}</option>`).join('')}</optgroup>`).join('')}</select></label><label class="field"><span>글 분류</span><select name="type">${['사용기','정보'].map(x=>`<option ${draft.type===x?'selected':''}>${x}</option>`).join('')}</select></label></div><div class="editor-tip">어떤 환경에서, 얼마나 사용했는지 알려 주세요.<br>광고·협찬이 포함되어 있다면 본문에 함께 밝혀 주세요.</div><label class="field"><span>제목 <small>필수 · 최대 100자</small></span><input name="title" required maxlength="100" placeholder="어떤 경험을 나누고 싶으신가요?" value="${esc(draft.title)}"></label><label class="field"><span>본문 <small>필수</small></span><textarea name="body" required maxlength="10000" placeholder="직접 사용한 경험과 나만의 팁을 자유롭게 적어 주세요.">${esc(draft.body)}</textarea></label><footer class="form-bottom"><p>서로의 취향을 존중하는 글을 작성해 주세요.<br>개인정보가 포함되지 않았는지 확인해 주세요.</p><button class="primary">게시글 등록 ↗</button></footer></form>`}
function admin(){const pending=reports.filter(r=>r.status==='대기').length;return `<header class="admin-header"><div><a class="brand" href="#home">EDC WORLD</a><span>ADMIN</span></div>${goLink('home','커뮤니티로 ↗')}</header><div class="admin-layout"><aside class="admin-rail"><p>COMMUNITY ADMIN</p><strong>▤ 게시글·신고 관리</strong><small>운영자 도윤<br>콘텐츠 운영 권한</small></aside><section class="admin-content"><div class="page-title"><div><p class="eyebrow">MODERATION</p><h1>게시글·신고 관리</h1><p>접수된 신고를 확인하고 게시글 공개 상태를 관리합니다.</p></div></div><div class="stat-grid"><div class="card stat attention"><small>검토 대기</small><b>${pending}</b><span>확인이 필요한 신고</span></div><div class="card stat"><small>공개 게시글</small><b>${entries.filter(p=>!p.hidden).length}</b><span>전체 게시판</span></div><div class="card stat"><small>처리 완료</small><b>${reports.length-pending}</b><span>검토한 신고</span></div></div><div class="card"><div class="admin-tabs"><button class="tab ${adminTab==='reports'?'on':''}" data-admin="reports">신고 관리 ${pending}</button><button class="tab ${adminTab==='posts'?'on':''}" data-admin="posts">게시글 관리</button></div>${adminTab==='reports'?reports.map(r=>{const p=getPost(r.post);return `<article class="moderation-row"><div><span class="status ${r.status!=='대기'?'done':''}">${esc(r.status==='대기'?'검토 대기':r.status)}</span><h3>${postLink(p)}</h3><p>${esc(r.reason)} · 신고 ${r.count}건<br>${esc(p.board)} · ${esc(p.user)} · 09.13 11:30</p>${r.resolution?`<p>처리 사유: ${esc(r.resolution)}</p>`:''}</div><div class="moderation-actions">${r.status==='대기'?`<button class="secondary" data-review="${r.id}">${reviewId===r.id?'검토 닫기':'검토하기'}</button>`:'<span class="meta">검토 완료</span>'}</div>${reviewId===r.id?`<form class="review-box" data-resolve="${r.id}"><p>신고 내용: ${esc(r.note)}</p><label>처리 사유<select name="reason"><option>커뮤니티 운영 정책 위반</option><option>광고·홍보 가이드 위반</option><option>위반 사항 없음</option></select></label><div class="actions"><button class="primary" name="action" value="hide">게시글 숨김</button><button class="secondary" name="action" value="dismiss">신고 기각</button></div></form>`:''}</article>`}).join(''):entries.map(p=>`<article class="moderation-row"><div><span class="status ${p.hidden?'':'done'}">${p.hidden?'숨김':'공개'}</span><h3>${postLink(p)}</h3><p>${esc(p.board)} · ${esc(p.user)} · 조회 ${p.views}</p></div><div class="moderation-actions"><button class="secondary" data-visibility="${p.id}">${p.hidden?'공개로 복원':'숨김 처리'}</button></div></article>`).join('')}</div><p class="admin-note">숨긴 글은 커뮤니티 목록에서 제외됩니다. 게시글 관리에서 다시 공개할 수 있습니다.</p></section></div>`}
function render(){const i=Object.keys(screens).indexOf(current);document.querySelector('#screen-nav').innerHTML=Object.entries(screens).map(([id,s],n)=>`<a href="#${id}" class="${id===current?'active':''}" ${id===current?'aria-current="page"':''}><span>0${n+1}</span>${s[0]}</a>`).join('');document.querySelector('#screen-number').textContent=`SCREEN 0${i+1} / EDC WORLD V9`;document.querySelector('#screen-title').textContent=screens[current][1];document.querySelector('#screen-description').textContent=screens[current][2];const body=current==='admin'?admin():shell(current==='home'?home():current==='board'?boardView():current==='detail'?detail():editor());document.querySelector('#artboards').innerHTML=['desktop','mobile'].map(device=>`<section><div class="frame-label"><b>0${i+1} / ${screens[current][0]} — ${device==='desktop'?'Desktop':'Mobile'}</b><span>${device==='desktop'?'1200':'390'} px</span></div><div class="device ${device}" aria-label="${device} ${screens[current][0]}"><div class="app">${body}</div></div></section>`).join('')}
function go(next){if(current===next){render();return}location.hash=next}
window.addEventListener('hashchange',()=>{current=screens[location.hash.slice(1)]?location.hash.slice(1):'home';render()});
let timer;function toast(t){const el=document.querySelector('.toast');el.textContent=t;el.classList.add('show');clearTimeout(timer);timer=setTimeout(()=>el.classList.remove('show'),2800)}
document.addEventListener('click',e=>{
 const el=e.target.closest('a,button');if(!el)return;
 if(el.dataset.board){e.preventDefault();board=el.dataset.board;query='';filter='전체';draft.board=board==='전체 게시판'?'사용기·리뷰':board;go('board')}
 else if(el.dataset.post){e.preventDefault();selected=el.dataset.post;go('detail')}
 else if(el.getAttribute('href')?.startsWith('#')){e.preventDefault();const next=el.getAttribute('href').slice(1);if(screens[next])go(next)}
 if(el.dataset.sort!==undefined){sort=Number(el.dataset.sort);render()}
 if(el.dataset.latest){latestGroup=el.dataset.latest;render()}
 if(el.dataset.filter){filter=el.dataset.filter;render()}
 if(el.dataset.like){liked.has(el.dataset.like)?liked.delete(el.dataset.like):liked.add(el.dataset.like);render()}
 if(el.dataset.report){if(reports.some(r=>r.post===el.dataset.report&&r.fromUser)){toast('이미 접수한 신고입니다.');return}reports.unshift({id:'r'+Date.now(),post:el.dataset.report,reason:'이용자 검토 요청',note:'이용자가 게시글 검토를 요청했습니다.',count:1,status:'대기',fromUser:true});toast('신고가 접수되었습니다. 관리자 화면에서 확인할 수 있습니다.')}
 if(el.dataset.admin){adminTab=el.dataset.admin;reviewId=null;render()}
 if(el.dataset.review){reviewId=reviewId===el.dataset.review?null:el.dataset.review;render()}
 if(el.dataset.visibility){const p=getPost(el.dataset.visibility);p.hidden=!p.hidden;render();toast(p.hidden?'게시글을 숨겼습니다.':'게시글을 다시 공개했습니다.')}
 if(el.hasAttribute('data-draft')){draft=Object.fromEntries(new FormData(el.closest('form')));toast('현재 탭에 임시 저장했습니다.')}
 if(el.dataset.zoom)setZoom(zoom+(el.dataset.zoom==='+'?.1:-.1));
 if(el.id==='fit')fit();
});
document.addEventListener('input',e=>{const form=e.target.closest('[data-editor]');if(!form)return;draft=Object.fromEntries(new FormData(form));document.querySelectorAll('[data-editor]').forEach(other=>{if(other!==form){const field=other.elements.namedItem(e.target.name);if(field)field.value=e.target.value}})});
document.addEventListener('submit',e=>{
 const f=e.target;e.preventDefault();const data=new FormData(f);
 if(f.dataset.search){query=String(data.get('query')).trim();filter='전체';if(f.dataset.search==='global')board='전체 게시판';go('board')}
 if(f.dataset.comment){const value=String(data.get('comment')).trim();if(!value)return;comments.set(f.dataset.comment,[...(comments.get(f.dataset.comment)||[]),value]);render();toast('댓글을 등록했습니다.')}
 if(f.hasAttribute('data-editor')){const title=String(data.get('title')).trim(),body=String(data.get('body')).trim();if(!title||!body){toast('제목과 본문을 입력해 주세요.');return}selected='new-'+Date.now();board=String(data.get('board'));entries.unshift({id:selected,board,type:String(data.get('type')),title,body,user:'도윤',views:'0',likes:0,comments:0,custom:true});draft={board,type:'사용기',title:'',body:''};query='';filter='전체';go('detail');toast('시안에 게시글을 등록했습니다.')}
 if(f.dataset.resolve){const r=reports.find(r=>r.id===f.dataset.resolve);const reason=String(data.get('reason'));const hiding=e.submitter?.value==='hide';if(hiding&&reason==='위반 사항 없음'){toast('숨김 처리에 맞는 사유를 선택해 주세요.');return}if(!hiding&&reason!=='위반 사항 없음'){toast('신고 기각 시 사유를 “위반 사항 없음”으로 선택해 주세요.');return}r.status=hiding?'숨김 처리':'기각';r.resolution=reason;if(hiding)getPost(r.post).hidden=true;reviewId=null;render();toast('신고 처리를 완료했습니다.')}
});
function setZoom(value){zoom=Math.max(.2,Math.min(1.25,value));document.documentElement.style.setProperty('--zoom',zoom);document.querySelector('#zoom-value').textContent=Math.round(zoom*100)+'%'}
function fit(){setZoom(Math.min(.85,document.querySelector('.board-scroll').clientWidth/1624))}
render();fit();
