const screens = {
  home: ['홈', '취향이 만나는 첫 화면', '품목별 커뮤니티로 들어가고, 오늘의 이야기와 인기 글 Top 10을 발견합니다.'],
  feed: ['피드 목록', '같은 물건, 서로 다른 이야기', '캐리 5개 품목과 자유·유머는 사진과 짧은 이야기가 흐르는 피드로 구성합니다.'],
  'feed-detail': ['피드 보기', '한 장에서 시작되는 대화', '사용자의 사진, 선택한 이유, 구성품, 공감과 댓글을 연결합니다.'],
  'feed-write': ['피드 작성', '오늘의 캐리를 꺼내놓기', '카테고리를 고르고 사진과 짧은 이야기를 올리는 가벼운 작성 흐름입니다.'],
  posts: ['정보 게시판', '경험이 쌓이는 정보 게시판', '정보 카테고리는 제목과 작성자 중심의 전통적인 게시판으로 구성합니다.'],
  'post-detail': ['포스트 보기', '오래 읽고, 다시 찾을 이야기', '긴 사용기와 정보성 글에 집중할 수 있도록 본문의 폭과 읽기 리듬을 정돈합니다.'],
  'post-write': ['포스트 작성', '나의 경험을 모두의 정보로', '제목과 장문 본문을 중심으로 정보성 글을 작성합니다.']
};
const categories = ['나이프','멀티툴','라이트','시계','피젯','정보','자유','유머'];
const icons = {
  나이프:'<path d="M6 22 22 6c2 6-1 11-7 12l-5 7-4-3Z"/><path d="m15 18-4-4"/>',
  멀티툴:'<path d="m11 13-3 13M19 13l3 13M11 13l4 4 4-4M11 13 9 4l6 5 6-5-2 9"/>',
  라이트:'<path d="M11 12h10v16H11zM9 7h14v5H9zM12 3v1m8-1v1M15 16h2v4h-2"/>',
  시계:'<circle cx="16" cy="16" r="8"/><path d="m12 9 1-7h6l1 7m-8 14 1 7h6l1-7m-4-12v5l3 2"/>',
  피젯:'<path d="M8 8h16v16H8zM12 4h16v16"/><circle cx="16" cy="16" r="3"/>',
  home:'<path d="m4 14 12-10 12 10M8 12v16h16V12M13 28V18h6v10"/>',
  feed:'<rect x="5" y="4" width="22" height="24" rx="3"/><path d="M5 21h22M10 16l5-5 5 6 3-3"/>',
  posts:'<path d="M7 4h18v24H7zM11 10h10M11 15h10M11 20h6"/>',
  write:'<path d="m7 21-2 6 6-2L27 9l-4-4L7 21Zm0 0 4 4"/>'
};
const icon = key => `<svg class="category-icon" viewBox="0 0 32 32" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[key] || icons.feed}</svg>`;
const photo = '../v2/assets/edc-flatlay.png';
let current = screens[location.hash.slice(1)] ? location.hash.slice(1) : 'home';
let category = '나이프', sort = '최신', zoom = .75, search = '';
const stories = categories.filter(x=>x!=='정보').flatMap((cat,i)=>[
  {id:`${i}-a`,cat,user:'도윤',title:cat==='나이프'?'손에 익은 것들만 남겼어요.':`${cat}, 오늘도 함께한 작은 물건.`,body:'매일 쓰다 보니 반짝임보다 손에 익은 감각이 좋아졌어요. 오늘 출근길에도 이 조합입니다.',likes:48,comments:12,photo},
  {id:`${i}-b`,cat,user:'소소',title:cat==='나이프'?'흠집도 취향이 되는 순간.':`오래 쓰는 ${cat}에는 이유가 있죠.`,body:'새것보다 편한, 3년째 함께하는 주머니 속 친구들. 여러분은 어떤 걸 오래 쓰고 있나요?',likes:32,comments:7,photo}
]);
const posts = ['작은 라이트를 고를 때, 밝기보다 먼저 본 것들','멀티툴을 1년 동안 써보고 남기는 기록','입문자를 위한 나이프 관리 노트','시계 스트랩을 바꾸니 달라진 착용감','주머니에 넣기 좋은 피젯, 소재별 사용감','배터리 교체형 라이트를 선택한 이유','나만의 캐리 구성, 가볍게 시작하는 법','오래 쓴 도구를 정리하고 보관하는 방법'].map((title,i)=>({id:`p${i}`,title,user:['하루','도윤','나무','소소'][i%4],type:i%2?'사용기':'가이드',views:324-i*27,comments:14-i}));
const ranking = ['손에 익은 것들만 남겼어요.','작은 라이트를 고르는 나만의 기준','멀티툴 하나로 해결한 주말','아버지에게 물려받은 시계','피젯을 내려놓을 수 없는 이유','흠집도 취향이 되는 순간','출근길, 주머니를 가볍게','매일 쓰는 도구의 관리 기록','오늘의 캐리, 검정과 초록','이 정도면 주머니가 본체 아닌가요'];
let selectedStory = stories[0], selectedPost = posts[0];
const liked = new Set(), saved = new Set(), comments = new Map(), drafts = {};
const escapeHTML = value => String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const goButton = (screen,text,cls='')=>`<button class="${cls}" data-go="${screen}">${text}</button>`;
function header(){return `<header class="app-header"><button class="brand" data-go="home"><span class="pocket-mark"></span>Pockets</button><nav aria-label="서비스 메뉴">${goButton('home','홈',current==='home'?'selected':'')}${goButton('feed','캐리',['feed','feed-detail','feed-write'].includes(current)?'selected':'')}${goButton('posts','정보',current.startsWith('post')?'selected':'')}</nav><div class="header-right"><span class="avatar" aria-label="예시 사용자 도윤">도</span>${goButton(current.startsWith('post')?'post-write':'feed-write','＋ 글쓰기','primary')}</div></header>`}
function bottom(){return `<nav class="bottom-nav" aria-label="모바일 메뉴">${[['home','홈'],['feed','캐리'],['posts','정보'],['feed-write','글쓰기']].map(([s,t])=>goButton(s,`${icon(s==='feed-write'?'write':s)}${t}`,s===current?'selected':'')).join('')}</nav>`}
function author(user='도윤',meta='나이프 · 2시간 전'){return `<div class="author"><span class="avatar ${user==='소소'?'rose':''}">${escapeHTML(user[0])}</span><div class="meta"><b>${escapeHTML(user)}</b><small>${escapeHTML(meta)}</small></div></div>`}
function reactions(item,isPost=false){const key=isPost?item.id:item.id;return `<div class="reactions"><button data-like="${key}" class="${liked.has(key)?'on':''}" aria-pressed="${liked.has(key)}">${liked.has(key)?'♥':'♡'} 공감 ${ (item.likes||36)+(liked.has(key)?1:0)}</button><button data-open="${item.id}" data-kind="${isPost?'post':'feed'}">댓글 ${item.comments+(comments.get(key)?.length||0)}</button><button class="save ${saved.has(key)?'on':''}" data-save="${key}" aria-pressed="${saved.has(key)}">${saved.has(key)?'✓ 저장됨':'＋ 저장'}</button></div>`}
function storyCard(item){return `<article class="story-card"><button class="post-link photo-wrap" data-open="${item.id}" data-kind="feed" aria-label="${escapeHTML(item.title)} 보기"><img class="story-photo" src="${item.photo}" alt="사용자가 펼쳐놓은 일상 휴대품" loading="lazy"></button><div class="story-content">${author(item.user,`${item.cat} · 2시간 전`)}<button class="post-link" data-open="${item.id}" data-kind="feed"><h3>${escapeHTML(item.title)}</h3></button><p>${escapeHTML(item.body)}</p>${reactions(item)}</div></article>`}
function categoryButtons(cls){return `<div class="${cls}">${categories.map(c=>`<button data-category="${c}" class="${c===category?'active':''}">${c}</button>`).join('')}</div>`}
function rail(){return `<aside class="category-rail"><p class="overline">CARRY</p>${categories.slice(0,5).map(c=>`<button data-category="${c}" class="${c===category?'active':''}">${c}</button>`).join('')}<p class="overline common-label">COMMUNITY</p>${categories.slice(5).map(c=>`<button data-category="${c}" class="${current.startsWith('post')&&c==='정보'?'active':''}">${c}</button>`).join('')}</aside>`}
function home(){return `<section class="welcome"><div><div class="eyebrow">Every Carry. Everyone's Story</div><h1>당신의 주머니에는<br>어떤 이야기가 있나요?</h1><p>매일 들고 다니는 물건, 그 안에 담긴 나다운 취향.</p></div><div class="pocket-drawing" aria-hidden="true"></div></section><section><div class="section-heading"><h2>취향이 통하는 곳</h2><small>무엇을 꺼내볼까요?</small></div><div class="category-grid">${categories.slice(0,5).map(c=>`<button class="category-card" data-category="${c}">${icon(c)}<strong>${c}</strong><small>이야기 둘러보기 <span>↗</span></small></button>`).join('')}</div><div class="common-categories"><span>함께 나눠요</span>${categories.slice(5).map(c=>`<button data-category="${c}">${c}<small>${c==='정보'?'POST':'FEED'}</small></button>`).join('')}</div></section><div class="home-bottom"><section><div class="section-heading"><h2>오늘의 주머니</h2>${goButton('feed','피드 더 보기 ↗','text-button')}</div>${storyCard(stories[0])}</section><section><div class="section-heading"><h2>이야기 Top 10</h2><small>오늘 · 공감순</small></div><ol class="rank-list">${ranking.map((t,i)=>`<li><span class="rank-number">${String(i+1).padStart(2,'0')}</span><button data-rank="${i}">${t}</button><small>♡ ${128-i*9}</small></li>`).join('')}</ol><p class="rank-foot">서로의 취향에 가장 많이 공감한 이야기</p></section></div>`}
function feed(){let items=stories.filter(s=>s.cat===category);if(sort==='인기')items=[...items].sort((a,b)=>b.likes-a.likes);return `${categoryButtons('category-strip')}<div class="content-grid">${rail()}<section><div class="feed-top"><div class="page-title"><div class="eyebrow">${['자유','유머'].includes(category)?'COMMUNITY':'CARRY'} / FEED</div><h1>${category}</h1><p>${category==='나이프'?'손에 익은 도구, 저마다의 쓰임과 취향.':`${category}에 담긴 각자의 이야기를 나눠요.`}</p></div>${goButton('feed-write','＋ 피드 쓰기','primary')}</div><div class="feed-tabs">${['최신','인기'].map(t=>`<button data-sort="${t}" class="${sort===t?'active':''}">${t}</button>`).join('')}</div><div class="feed-grid">${items.map(storyCard).join('')}</div><div class="prompt"><p><small>YOUR POCKET, YOUR STORY</small>완벽한 구성이 아니어도 괜찮아요.</p>${goButton('feed-write','내 이야기 쓰기 ↗','text-button')}</div></section></div>`}
function commentSection(item){return `<section class="comments"><h2>댓글 ${item.comments+(comments.get(item.id)?.length||0)}</h2><div class="comment"><span class="avatar rose">소</span><div><b>소소</b><small>1시간 전</small><p>오래 함께한 물건에 더 마음이 가는 것 같아요.<br>사용한 이야기도 자주 들려주세요!</p></div></div>${(comments.get(item.id)||[]).map(t=>`<div class="comment"><span class="avatar">도</span><div><b>도윤</b><small>방금 전</small><p>${escapeHTML(t)}</p></div></div>`).join('')}<form class="comment-form" data-comment="${item.id}"><input name="comment" aria-label="댓글" placeholder="취향이 통하는 한마디를 남겨보세요." required maxlength="500"><button class="primary">등록</button></form></section>`}
function feedDetail(){const s=selectedStory;return `<div class="reading"><div class="breadcrumb">${goButton('feed',`← ${escapeHTML(s.cat)} 피드로`,'text-button')}</div><div class="eyebrow">${escapeHTML(s.cat)} / DAILY CARRY</div><h1>${escapeHTML(s.title)}</h1>${author(s.user,`${s.cat} · 2026.09.07 · 조회 248`)}${s.photo?`<img class="detail-photo" src="${s.photo}" alt="이야기와 함께 공유한 캐리 구성">`:''}<div class="body-copy"><p>${escapeHTML(s.body).replace(/\n/g,'<br>')}</p>${!s.custom?'<p>처음에는 하나씩 더하는 재미였는데, 요즘은 하나씩 덜어내고 있어요.<br>많이 꺼내 쓰는 것만 남기니 주머니도, 아침의 선택도 한결 가볍네요.</p>':''}</div><div class="item-list">${(s.items||'매일 쓰는 것들,출퇴근,사용 기록').split(',').map(t=>`<span>${escapeHTML(t.trim())}</span>`).join('')}</div>${reactions(s)}${commentSection(s)}</div>`}
function postsView(){const filtered=posts.filter(p=>p.title.includes(search));return `${categoryButtons('category-strip')}<div class="content-grid">${rail()}<section><div class="feed-top"><div class="page-title"><div class="eyebrow">COMMUNITY / POST</div><h1>정보</h1><p>직접 써보고 알게 된 것들. 오래 남을 경험을 나눠요.</p></div>${goButton('post-write','＋ 글쓰기','primary')}</div><form class="board-search"><input name="search" aria-label="정보 글 검색" placeholder="제목으로 정보 찾기" value="${escapeHTML(search)}"><button class="secondary">검색</button></form><table class="post-table"><thead><tr><th>제목</th><th>작성자</th><th>날짜</th><th>조회</th></tr></thead><tbody>${filtered.map(p=>`<tr><td><button data-open="${p.id}" data-kind="post"><span class="tag">${escapeHTML(p.type)}</span>${escapeHTML(p.title)}<small>${p.comments+(comments.get(p.id)?.length||0)}</small></button></td><td>${escapeHTML(p.user)}</td><td>09.07</td><td>${p.views}</td></tr>`).join('')}</tbody></table>${!filtered.length?'<p class="empty">검색 결과가 없습니다. 다른 제목으로 찾아보세요.</p>':''}<p class="rank-foot">${filtered.length}개의 이야기 · 예시 게시판</p></section></div>`}
function postDetail(){const p=selectedPost;return `<article class="reading"><div class="breadcrumb">${goButton('posts','← 정보 게시판으로','text-button')}</div><div class="eyebrow">정보 / ${escapeHTML(p.type)}</div><h1>${escapeHTML(p.title)}</h1>${author(p.user,`2026.09.07 · 조회 ${p.views}`)}<div class="body-copy">${p.body?`<p>${escapeHTML(p.body).replace(/\n/g,'<br>')}</p>`:p.id==='p0'?`<p>처음에는 숫자가 큰 라이트가 좋은 라이트라고 생각했어요. 그런데 매일 들고 다니다 보니, 실제로 손이 가는 기준은 조금 달랐습니다.</p><div class="article-note">제가 쓰는 환경<br>도보 출퇴근, 가끔 하는 저녁 산책, 가방 안에서 물건 찾기.<br>제 생활을 기준으로 정리한 개인적인 사용기입니다.</div><h2>01. 주머니에서 부담이 없는가</h2><p>성능이 좋아도 집에 두고 나오면 소용이 없더라고요. 앉았을 때 불편하지 않은 길이와 무게, 손에 걸리지 않는 클립을 먼저 살펴봤습니다.</p><h2>02. 자주 쓰는 밝기로 바로 켤 수 있는가</h2><p>어두운 방에서 작은 물건을 찾을 때는 낮은 밝기를 자주 씁니다. 매번 여러 번 눌러야 하는지, 이전 설정을 기억하는지가 실제 사용에서는 더 크게 느껴졌어요.</p><h2>03. 계속 관리할 수 있는가</h2><p>충전 방식과 배터리 교체가 제 생활에 맞는지도 확인했습니다. 정해진 정답보다는, 오래 들고 다닐 수 있는 쪽을 선택하게 되네요.</p><p>여러분이 직접 써보며 바꾼 선택 기준도 궁금합니다. 댓글로 함께 이야기해 주세요.</p>`:`<p>${escapeHTML(p.title)}에 관한 개인적인 경험을 나눕니다.</p><h2>매일 쓰면서 알게 된 점</h2><p>처음의 기대와 실제 사용감은 조금 달랐습니다. 짧게 만져볼 때보다 매일 들고 다니면서, 내 생활에 맞는 크기와 감각을 더 잘 알게 되었어요.</p><div class="article-note">오래 쓰는 물건의 기준은 각자의 생활에 따라 달라집니다. 사용한 환경과 함께 경험을 나눠주세요.</div><h2>계속 사용하게 되는 이유</h2><p>특별한 순간보다 일상의 작은 불편을 해결해 주는 점이 좋았습니다. 여러분은 어떤 점을 가장 중요하게 보시나요?</p>`}</div>${reactions(p,true)}${commentSection(p)}</article>`}
function editor(isPost,device){const type=isPost?'post':'feed',d=drafts[type]||{},prefix=`${device}-${type}`;return `<form class="editor" data-editor="${type}"><div class="breadcrumb">${goButton(isPost?'posts':'feed','← 돌아가기','text-button')}</div><header class="editor-header"><div><div class="eyebrow">${isPost?'SHARE YOUR EXPERIENCE':'OPEN YOUR POCKET'}</div><h1>${isPost?'정보 글 쓰기':'오늘의 캐리 쓰기'}</h1></div><button type="button" class="secondary" data-draft>임시 저장</button></header><label class="field"><span>카테고리</span><select name="category" aria-label="작성 카테고리">${(isPost?['정보']:categories.filter(c=>c!=='정보')).map(c=>`<option ${c===(d.category||category)?'selected':''}>${c}</option>`).join('')}</select></label>${isPost?`<label class="field"><span>글 유형</span><select name="type"><option ${d.type==='가이드'?'selected':''}>가이드</option><option ${d.type==='사용기'?'selected':''}>사용기</option></select></label>`:`<div class="field"><span>사진 <small>선택 · 내 캐리가 잘 보이는 한 장</small></span><div class="upload"><span class="upload-icon">＋</span><strong>오늘의 주머니를 보여주세요</strong><small>JPG, PNG, WEBP · 최대 10MB</small><input id="${prefix}-photo" aria-label="캐리 사진 추가" name="photo" type="file" accept="image/jpeg,image/png,image/webp"></div></div>`}<label class="field"><span>제목</span><input name="title" value="${escapeHTML(d.title||'')}" placeholder="${isPost?'어떤 경험을 나누고 싶나요?':'예: 손에 익은 것들만 남겼어요.'}" required maxlength="100"></label><label class="field"><span>${isPost?'본문':'이야기'}</span><textarea name="body" rows="${isPost?12:5}" placeholder="${isPost?'어떤 환경에서, 얼마나 사용했는지부터 이야기해 주세요.\n직접 알게 된 점과 나만의 팁을 자유롭게 적어주세요.':'오늘 어디에 함께했나요?\n고른 이유나 직접 써본 이야기를 들려주세요.'}" required>${escapeHTML(d.body||'')}</textarea></label>${!isPost?`<label class="field"><span>함께한 구성품 <small>선택</small></span><input name="items" value="${escapeHTML(d.items||'')}" placeholder="제품명이나 모델명을 쉼표로 구분해 주세요."></label>`:''}<footer class="form-bottom"><p>서로의 취향을 존중하며 이야기를 나눠요.<br>이 시안의 등록·임시 저장은 현재 탭에서만 유지됩니다.</p><button class="primary" type="submit">${isPost?'정보 게시판에 등록':'피드에 올리기'} ↗</button></footer></form>`}
function render(){const idx=Object.keys(screens).indexOf(current);document.querySelector('#screen-nav').innerHTML=Object.entries(screens).map(([k,v],i)=>`<a href="#${k}" class="${current===k?'active':''}" ${current===k?'aria-current="page"':''}><span>${String(i+1).padStart(2,'0')}</span>${v[0]}</a>`).join('');document.querySelector('#screen-number').textContent=`SCREEN ${String(idx+1).padStart(2,'0')} / POCKETS V7`;document.querySelector('#screen-title').textContent=screens[current][1];document.querySelector('#screen-description').textContent=screens[current][2];document.querySelector('#artboards').innerHTML=['desktop','mobile'].map(device=>{const body=current==='home'?home():current==='feed'?feed():current==='feed-detail'?feedDetail():current==='posts'?postsView():current==='post-detail'?postDetail():editor(current==='post-write',device);return `<section><div class="frame-label"><b>${String(idx+1).padStart(2,'0')} / ${screens[current][0]} — ${device==='desktop'?'Desktop':'Mobile'}</b><span>${device==='desktop'?'1120':'390'} px</span></div><div class="frame ${device}" aria-label="${device} ${screens[current][0]}">${header()}<div class="app-main">${body}</div><footer class="app-footer"><b>Pockets</b><span>Every Carry. Everyone's Story</span><span>각자의 취향이 모이는 곳</span></footer>${bottom()}</div></section>`}).join('')}
function go(screen){if(screen===current){render();return}location.hash=screen}
window.addEventListener('hashchange',()=>{current=screens[location.hash.slice(1)]?location.hash.slice(1):'home';render()});
let toastTimer;function toast(text){const el=document.querySelector('.toast');el.textContent=text;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),2600)}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.go)go(b.dataset.go);if(b.dataset.category){category=b.dataset.category;if(category==='정보')go('posts');else go('feed')}if(b.dataset.open){if(b.dataset.kind==='post'){selectedPost=posts.find(p=>p.id===b.dataset.open);go('post-detail')}else{selectedStory=stories.find(p=>p.id===b.dataset.open);category=selectedStory.cat;go('feed-detail')}}if(b.dataset.rank!==undefined){const i=Number(b.dataset.rank);if(i===1||i===7){selectedPost=posts[i===1?0:7];go('post-detail')}else{const ids=[0,0,2,6,8,1,10,0,4,12];selectedStory={...stories[ids[i]],title:ranking[i]};category=selectedStory.cat;go('feed-detail')}}if(b.dataset.sort){sort=b.dataset.sort;render()}for(const [attr,set] of [['like',liked],['save',saved]])if(b.dataset[attr]){const id=b.dataset[attr];if(set.has(id))set.delete(id);else set.add(id);document.querySelectorAll(`[data-${attr}="${id}"]`).forEach(el=>{el.classList.toggle('on',set.has(id));el.setAttribute('aria-pressed',String(set.has(id)));if(attr==='save')el.textContent=set.has(id)?'✓ 저장됨':'＋ 저장';else{const item=stories.find(s=>s.id===id)||posts.find(p=>p.id===id);el.textContent=`${set.has(id)?'♥':'♡'} 공감 ${(item.likes||36)+(set.has(id)?1:0)}`}})}if(b.hasAttribute('data-draft')){const f=b.closest('form');drafts[f.dataset.editor]=Object.fromEntries(new FormData(f));toast('현재 탭에 임시 저장했어요. 사진은 다시 선택해 주세요.')}if(b.dataset.zoom){setZoom(zoom+(b.dataset.zoom==='+'?.1:-.1))}if(b.id==='fit')fit()});
document.addEventListener('submit',e=>{e.preventDefault();const form=e.target,data=new FormData(form);if(form.classList.contains('comment-form')){const value=data.get('comment').trim();if(!value)return;const id=form.dataset.comment;comments.set(id,[...(comments.get(id)||[]),value]);render();toast('댓글을 남겼어요.')}if(form.classList.contains('board-search')){search=data.get('search').trim();render()}if(form.dataset.editor){const title=data.get('title').trim(),body=data.get('body').trim();if(!title||!body){toast('제목과 내용을 입력해 주세요.');return}const id=`new-${Date.now()}`;if(form.dataset.editor==='post'){selectedPost={id,title,body,user:'도윤',type:data.get('type'),views:0,comments:0};posts.unshift(selectedPost);search='';delete drafts.post;go('post-detail')}else{const file=data.get('photo');selectedStory={id,title,body,user:'도윤',cat:data.get('category'),items:data.get('items')||'나의 캐리',likes:0,comments:0,custom:true,photo:file?.size?URL.createObjectURL(file):photo};stories.unshift(selectedStory);category=selectedStory.cat;delete drafts.feed;go('feed-detail')}toast('시안에 등록했어요. 새로고침하면 초기화됩니다.')}});
document.addEventListener('change',e=>{if(e.target.type!=='file')return;const file=e.target.files[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024){toast('10MB 이하의 JPG, PNG, WEBP 사진을 선택해 주세요.');e.target.value='';return}const box=e.target.closest('.upload');box.querySelector('img')?.remove();box.querySelectorAll('span,strong,small').forEach(x=>x.hidden=true);const img=document.createElement('img');img.alt='선택한 캐리 사진 미리보기';img.src=URL.createObjectURL(file);img.onload=()=>URL.revokeObjectURL(img.src);box.prepend(img)});
function setZoom(value){zoom=Math.max(.25,Math.min(1.25,value));document.documentElement.style.setProperty('--zoom',zoom);document.querySelector('#zoom-value').textContent=`${Math.round(zoom*100)}%`}
function fit(){setZoom(Math.min(.85,document.querySelector('.board-scroll').clientWidth/1546))}
render();fit();
